token: ""
db_path: "storage/mathbattle.sqlite"

# Задачи и решения в виде фотографий не пишутся напрямую в базу, а копируются в директории,
# Чтобы жюри могло их легко посмотреть
problems_path: "storage/problem_storage"
solutions_path: "storage/solution_storage"
