# Telegram API token
telegram_token: ""

# Host and port of mbserver
api_url: "127.0.0.1:8080"

# Database settings
# Sqlite3
db_type: "sqlite3"
# Path to database file
db_connection_string: "storage/mathbattle.sqlite"

# Postgres
# db_type: "postgres"
# golang postgres connection string
# db_connection_string: "host=%s user=%s password=%s dbname=%s sslmode=disable"

# Задачи и решения в виде фотографий не пишутся напрямую в базу, а копируются в директории,
# Чтобы жюри могло их легко посмотреть
problems_path: "storage/problem_storage"
solutions_path: "storage/solution_storage"
